name: CI
on:
  pull_request:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest ruff black
      - name: Lint/Format (non-blocking)
        run: |
          ruff check . || true
          black --check . || true
      - name: Import smoke
        run: python -c "import fastapi, langgraph, httpx"
      - name: Eval (if sample exists, non-blocking)
        run: |
          if [ -f docs/schemas/healthcare_headers.txt ] && [ -f runs/latest/healthcare.csv ]; then             python -m evals.schema_validate --schema docs/schemas/healthcare_headers.txt --csv runs/latest/healthcare.csv || true;           fi
